services:
  my-service-production:
    container_name: my-service-production
    build:
      target: production
      context: .
      args:
        - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"

  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "9229:9229"
    volumes:
      - ./src:/app/src
    depends_on:
      - subscription_db-dev
  subscription_db-dev:
    container_name: db-dev
    image: postgres:14.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER_DEV:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV:-root}
      POSTGRES_DB: subscription_db
    ports:
      - "5434:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
